# Generated by Django 2.2.4 on 2019-08-21 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('birthday', '0003_guest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest',
            name='price',
            field=models.DecimalField(decimal_places=2, default=5.0, max_digits=20),
        ),
    ]
