# Generated by Django 2.2.4 on 2019-08-26 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('birthday', '0005_hellodate'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventtype',
            name='dam',
            field=models.DecimalField(decimal_places=2, default=5000.0, max_digits=20),
        ),
    ]
