# Generated by Django 2.2.4 on 2019-08-23 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('birthday', '0005_hellodate'),
        ('carts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='date',
        ),
        migrations.AddField(
            model_name='cart',
            name='date',
            field=models.ManyToManyField(to='birthday.HelloDate'),
        ),
        migrations.RemoveField(
            model_name='cart',
            name='eventtype',
        ),
        migrations.AddField(
            model_name='cart',
            name='eventtype',
            field=models.ManyToManyField(to='birthday.EventType'),
        ),
        migrations.RemoveField(
            model_name='cart',
            name='forwhom',
        ),
        migrations.AddField(
            model_name='cart',
            name='forwhom',
            field=models.ManyToManyField(to='birthday.ForWhom'),
        ),
        migrations.RemoveField(
            model_name='cart',
            name='guest',
        ),
        migrations.AddField(
            model_name='cart',
            name='guest',
            field=models.ManyToManyField(to='birthday.Guest'),
        ),
    ]
