# Generated by Django 2.2.4 on 2019-08-26 02:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0004_cart_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='date',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='eventtype',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='forwhom',
        ),
    ]
