# Generated by Django 2.2.4 on 2019-08-28 06:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('birthday', '0006_eventtype_dam'),
        ('carts', '0006_cart_eventtype'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='date',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='birthday.HelloDate'),
        ),
        migrations.AddField(
            model_name='cart',
            name='forwhom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='birthday.ForWhom'),
        ),
        migrations.RemoveField(
            model_name='cart',
            name='guest',
        ),
        migrations.AddField(
            model_name='cart',
            name='guest',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='birthday.Guest'),
        ),
    ]
